export type Voice = {
    id: string;              // Internal app ID
    googleVoiceId: string;   // Google Cloud TTS voice name
    name: string;            // Korean display name
    nameEn: string;          // English name
    description: string;     // Korean description
    avatar: string;          // Avatar URL
    tags: string[];          // Korean tags
    gender: 'Male' | 'Female' | 'Neutral';
    language: string;        // Display language label
    accent: string;          // Voice style/accent
    age: string;             // young, middle_aged, old
    useCase: string;         // Recommended use case
    previewUrl: string;      // Preview audio URL (empty = use TTS to generate)
    sampleText: string;      // Sample text for TTS preview
};

// Helper: Generate avatar URL with Korean initials
const avatar = (name: string, bg: string, color: string = 'fff') =>
    `https://ui-avatars.com/api/?name=${encodeURIComponent(name)}&background=${bg}&color=${color}&size=128&bold=true&font-size=0.4`;

export const VOICES: Voice[] = [
    // ===================================================================
    // 🇰🇷 KOREAN VOICES — Google Cloud TTS (Chirp3-HD = 최고 품질)
    // ===================================================================

    // --- 여성 (Female) ---
    {
        id: 'achernar',
        googleVoiceId: 'ko-KR-Chirp3-HD-Achernar',
        name: '아케르나르',
        nameEn: 'Achernar',
        description: '맑고 자연스러운 HD 여성 보이스. 깨끗한 발음과 따뜻한 톤으로 내레이션에 최적화되어 있습니다.',
        avatar: avatar('아케', '6366f1'),
        tags: ['맑은', '내레이션', 'HD'],
        gender: 'Female',
        language: '한국어',
        accent: '표준어',
        age: 'young',
        useCase: 'narration',
        previewUrl: '',
        sampleText: '안녕하세요, 저는 아케르나르입니다. 오늘 하루도 좋은 일이 가득하길 바랍니다.',
    },
    {
        id: 'aoede',
        googleVoiceId: 'ko-KR-Chirp3-HD-Aoede',
        name: '아오에데',
        nameEn: 'Aoede',
        description: '부드럽고 감성적인 HD 여성 보이스. 오디오북과 스토리텔링에 몰입감을 선사합니다.',
        avatar: avatar('아오', 'ec4899'),
        tags: ['감성', '오디오북', '스토리'],
        gender: 'Female',
        language: '한국어',
        accent: '표준어',
        age: 'young',
        useCase: 'audiobook',
        previewUrl: '',
        sampleText: '그 해 봄, 벚꽃이 눈처럼 흩날리던 날. 우리는 처음 만났습니다.',
    },
    {
        id: 'autonoe',
        googleVoiceId: 'ko-KR-Chirp3-HD-Autonoe',
        name: '오토노에',
        nameEn: 'Autonoe',
        description: '차분하고 전문적인 HD 여성 보이스. 교육 콘텐츠와 기업 PR에 신뢰감 있는 톤을 제공합니다.',
        avatar: avatar('오토', '14b8a6'),
        tags: ['전문적', '교육', '신뢰감'],
        gender: 'Female',
        language: '한국어',
        accent: '표준어',
        age: 'middle_aged',
        useCase: 'educational',
        previewUrl: '',
        sampleText: '오늘 알려드릴 내용은 여러분의 비즈니스에 큰 도움이 될 것입니다.',
    },
    {
        id: 'callirrhoe',
        googleVoiceId: 'ko-KR-Chirp3-HD-Callirrhoe',
        name: '칼리로에',
        nameEn: 'Callirrhoe',
        description: '밝고 활기찬 HD 여성 보이스. 유튜브와 소셜 미디어에서 친근한 분위기를 만듭니다.',
        avatar: avatar('칼리', 'f43f5e'),
        tags: ['밝은', '유튜브', '활기찬'],
        gender: 'Female',
        language: '한국어',
        accent: '표준어',
        age: 'young',
        useCase: 'social_media',
        previewUrl: '',
        sampleText: '안녕하세요 여러분! 오늘은 정말 재미있는 이야기를 준비했어요!',
    },
    {
        id: 'despina',
        googleVoiceId: 'ko-KR-Chirp3-HD-Despina',
        name: '데스피나',
        nameEn: 'Despina',
        description: '따뜻하고 편안한 HD 여성 보이스. ASMR과 명상 콘텐츠에 적합한 안정적인 톤입니다.',
        avatar: avatar('데스', 'a855f7'),
        tags: ['편안한', '명상', 'ASMR'],
        gender: 'Female',
        language: '한국어',
        accent: '표준어',
        age: 'young',
        useCase: 'meditation',
        previewUrl: '',
        sampleText: '깊은 호흡을 하고, 천천히 눈을 감아보세요.',
    },
    {
        id: 'erinome',
        googleVoiceId: 'ko-KR-Chirp3-HD-Erinome',
        name: '에리노메',
        nameEn: 'Erinome',
        description: '당당하고 세련된 HD 여성 보이스. 광고와 프레젠테이션에서 임팩트 있는 전달력을 보여줍니다.',
        avatar: avatar('에리', 'd946ef'),
        tags: ['세련된', '광고', '임팩트'],
        gender: 'Female',
        language: '한국어',
        accent: '표준어',
        age: 'young',
        useCase: 'advertising',
        previewUrl: '',
        sampleText: '지금 바로 만나보세요. 당신의 일상이 달라집니다.',
    },
    {
        id: 'gacrux',
        googleVoiceId: 'ko-KR-Chirp3-HD-Gacrux',
        name: '가크룩스',
        nameEn: 'Gacrux',
        description: '깊고 지적인 HD 여성 보이스. 다큐멘터리와 뉴스 해설에 무게감 있는 전달을 합니다.',
        avatar: avatar('가크', '06b6d4'),
        tags: ['지적', '다큐', '뉴스'],
        gender: 'Female',
        language: '한국어',
        accent: '표준어',
        age: 'middle_aged',
        useCase: 'news',
        previewUrl: '',
        sampleText: '오늘의 주요 뉴스를 전해드리겠습니다.',
    },
    {
        id: 'kore',
        googleVoiceId: 'ko-KR-Chirp3-HD-Kore',
        name: '코레',
        nameEn: 'Kore',
        description: '상냥하고 친근한 HD 여성 보이스. 튜토리얼과 가이드에서 이해하기 쉬운 설명을 합니다.',
        avatar: avatar('코레', 'fb923c'),
        tags: ['친근한', '튜토리얼', '가이드'],
        gender: 'Female',
        language: '한국어',
        accent: '표준어',
        age: 'young',
        useCase: 'tutorial',
        previewUrl: '',
        sampleText: '자, 그러면 지금부터 하나하나 차근차근 알려드릴게요.',
    },
    {
        id: 'laomedeia',
        googleVoiceId: 'ko-KR-Chirp3-HD-Laomedeia',
        name: '라오메데이아',
        nameEn: 'Laomedeia',
        description: '고급스럽고 우아한 HD 여성 보이스. 럭셔리 브랜드와 패션 콘텐츠에 품격을 더합니다.',
        avatar: avatar('라오', '4338ca'),
        tags: ['우아한', '럭셔리', '브랜드'],
        gender: 'Female',
        language: '한국어',
        accent: '표준어',
        age: 'middle_aged',
        useCase: 'luxury',
        previewUrl: '',
        sampleText: '세련된 감각으로 완성되는 특별한 순간을 경험하세요.',
    },
    {
        id: 'leda',
        googleVoiceId: 'ko-KR-Chirp3-HD-Leda',
        name: '레다',
        nameEn: 'Leda',
        description: '자연스럽고 부드러운 HD 여성 보이스. 일상 대화와 팟캐스트에 편안한 톤을 제공합니다.',
        avatar: avatar('레다', '059669'),
        tags: ['자연스러운', '팟캐스트', '일상'],
        gender: 'Female',
        language: '한국어',
        accent: '표준어',
        age: 'young',
        useCase: 'conversational',
        previewUrl: '',
        sampleText: '그래서 제가 오늘 이야기하고 싶은 건요, 사실 아주 간단한 거예요.',
    },
    {
        id: 'pulcherrima',
        googleVoiceId: 'ko-KR-Chirp3-HD-Pulcherrima',
        name: '풀케리마',
        nameEn: 'Pulcherrima',
        description: '깨끗하고 또렷한 HD 여성 보이스. 안내 멘트와 ARS에 명확한 전달을 합니다.',
        avatar: avatar('풀케', '0891b2'),
        tags: ['또렷한', '안내', 'ARS'],
        gender: 'Female',
        language: '한국어',
        accent: '표준어',
        age: 'middle_aged',
        useCase: 'announcement',
        previewUrl: '',
        sampleText: '전화 주셔서 감사합니다. 원하시는 서비스를 선택해 주세요.',
    },
    {
        id: 'sulafat',
        googleVoiceId: 'ko-KR-Chirp3-HD-Sulafat',
        name: '술라팟',
        nameEn: 'Sulafat',
        description: '에너지 넘치는 HD 여성 보이스. 게이밍과 엔터테인먼트에 생동감 있는 느낌을 줍니다.',
        avatar: avatar('술라', 'f59e0b'),
        tags: ['에너지', '게이밍', '엔터'],
        gender: 'Female',
        language: '한국어',
        accent: '표준어',
        age: 'young',
        useCase: 'entertainment',
        previewUrl: '',
        sampleText: '어머, 이건 진짜 대박이에요! 빨리 와서 확인해보세요!',
    },
    {
        id: 'vindemiatrix',
        googleVoiceId: 'ko-KR-Chirp3-HD-Vindemiatrix',
        name: '빈데미아트릭스',
        nameEn: 'Vindemiatrix',
        description: '차분하고 사려 깊은 HD 여성 보이스. 에세이와 문학 낭독에 감성적인 울림을 담습니다.',
        avatar: avatar('빈데', '7c3aed'),
        tags: ['차분한', '에세이', '문학'],
        gender: 'Female',
        language: '한국어',
        accent: '표준어',
        age: 'middle_aged',
        useCase: 'literature',
        previewUrl: '',
        sampleText: '가을이 오면 나는 언제나 그 골목을 떠올린다.',
    },
    {
        id: 'zephyr',
        googleVoiceId: 'ko-KR-Chirp3-HD-Zephyr',
        name: '제퍼',
        nameEn: 'Zephyr',
        description: '산뜻하고 경쾌한 HD 여성 보이스. 라이프스타일과 여행 콘텐츠에 밝은 분위기를 더합니다.',
        avatar: avatar('제퍼', '2563eb'),
        tags: ['산뜻한', '여행', '라이프'],
        gender: 'Female',
        language: '한국어',
        accent: '표준어',
        age: 'young',
        useCase: 'lifestyle',
        previewUrl: '',
        sampleText: '오늘은 서울의 숨겨진 카페를 찾아 떠나볼까요?',
    },

    // --- 남성 (Male) ---
    {
        id: 'achird',
        googleVoiceId: 'ko-KR-Chirp3-HD-Achird',
        name: '아키르드',
        nameEn: 'Achird',
        description: '따뜻하고 깊은 HD 남성 보이스. 다큐멘터리와 내레이션에 신뢰감 있는 톤을 제공합니다.',
        avatar: avatar('아키', '1e293b'),
        tags: ['따뜻한', '다큐', '신뢰감'],
        gender: 'Male',
        language: '한국어',
        accent: '표준어',
        age: 'middle_aged',
        useCase: 'narration',
        previewUrl: '',
        sampleText: '그 이야기는 오래 전, 아무도 기억하지 않는 시절에 시작되었습니다.',
    },
    {
        id: 'algenib',
        googleVoiceId: 'ko-KR-Chirp3-HD-Algenib',
        name: '알제니브',
        nameEn: 'Algenib',
        description: '에너지 넘치는 젊은 HD 남성 보이스. 유튜브와 숏폼에서 역동적인 전달력을 보여줍니다.',
        avatar: avatar('알제', '4338ca'),
        tags: ['에너지', '유튜브', '숏폼'],
        gender: 'Male',
        language: '한국어',
        accent: '표준어',
        age: 'young',
        useCase: 'social_media',
        previewUrl: '',
        sampleText: '안녕하세요 여러분! 오늘도 재미있는 영상 가져왔습니다!',
    },
    {
        id: 'charon',
        googleVoiceId: 'ko-KR-Chirp3-HD-Charon',
        name: '카론',
        nameEn: 'Charon',
        description: '낮고 묵직한 HD 남성 보이스. 미스터리와 공포 장르에서 긴장감을 극대화합니다.',
        avatar: avatar('카론', '475569'),
        tags: ['묵직한', '미스터리', '공포'],
        gender: 'Male',
        language: '한국어',
        accent: '표준어',
        age: 'middle_aged',
        useCase: 'mystery',
        previewUrl: '',
        sampleText: '그 방 안에서는, 아무도 나올 수 없었습니다.',
    },
    {
        id: 'enceladus',
        googleVoiceId: 'ko-KR-Chirp3-HD-Enceladus',
        name: '엔셀라두스',
        nameEn: 'Enceladus',
        description: '명쾌하고 자신감 있는 HD 남성 보이스. 비즈니스 프레젠테이션과 강연에 적합합니다.',
        avatar: avatar('엔셀', '0891b2'),
        tags: ['명쾌한', '비즈니스', '강연'],
        gender: 'Male',
        language: '한국어',
        accent: '표준어',
        age: 'middle_aged',
        useCase: 'corporate',
        previewUrl: '',
        sampleText: '이번 분기 매출은 전년 대비 30% 성장했습니다.',
    },
    {
        id: 'fenrir',
        googleVoiceId: 'ko-KR-Chirp3-HD-Fenrir',
        name: '펜리르',
        nameEn: 'Fenrir',
        description: '강렬하고 파워풀한 HD 남성 보이스. 게이밍과 액션 콘텐츠에 힘 있는 임팩트를 줍니다.',
        avatar: avatar('펜리', '7c3aed'),
        tags: ['강렬한', '게이밍', '액션'],
        gender: 'Male',
        language: '한국어',
        accent: '표준어',
        age: 'young',
        useCase: 'gaming',
        previewUrl: '',
        sampleText: '후퇴는 없다! 끝까지 전진하라!',
    },
    {
        id: 'iapetus',
        googleVoiceId: 'ko-KR-Chirp3-HD-Iapetus',
        name: '이아페투스',
        nameEn: 'Iapetus',
        description: '차분하고 점잖은 HD 남성 보이스. 뉴스와 리포트에서 안정적인 진행을 합니다.',
        avatar: avatar('이아', '3b82f6'),
        tags: ['차분한', '뉴스', '리포트'],
        gender: 'Male',
        language: '한국어',
        accent: '표준어',
        age: 'middle_aged',
        useCase: 'news',
        previewUrl: '',
        sampleText: '지금부터 오늘의 주요 뉴스를 전해드리겠습니다.',
    },
    {
        id: 'orus',
        googleVoiceId: 'ko-KR-Chirp3-HD-Orus',
        name: '오루스',
        nameEn: 'Orus',
        description: '편안하고 친근한 HD 남성 보이스. 팟캐스트와 대화형 콘텐츠에 자연스러운 톤을 제공합니다.',
        avatar: avatar('오루', '059669'),
        tags: ['편안한', '팟캐스트', '친근한'],
        gender: 'Male',
        language: '한국어',
        accent: '표준어',
        age: 'young',
        useCase: 'conversational',
        previewUrl: '',
        sampleText: '그래서 말인데요, 이거 진짜 흥미로운 이야기거든요.',
    },
    {
        id: 'puck',
        googleVoiceId: 'ko-KR-Chirp3-HD-Puck',
        name: '퍽',
        nameEn: 'Puck',
        description: '장난기 있고 유쾌한 HD 남성 보이스. 코미디와 엔터테인먼트에 재미를 더합니다.',
        avatar: avatar('퍽', 'f43f5e'),
        tags: ['유쾌한', '코미디', '재미'],
        gender: 'Male',
        language: '한국어',
        accent: '표준어',
        age: 'young',
        useCase: 'entertainment',
        previewUrl: '',
        sampleText: '여러분, 이거 한번 들어보시면 배꼽 잡으실 겁니다!',
    },
    {
        id: 'sadachbia',
        googleVoiceId: 'ko-KR-Chirp3-HD-Sadachbia',
        name: '사다키비아',
        nameEn: 'Sadachbia',
        description: '진중하고 깊은 HD 남성 보이스. 오디오북과 역사 내레이션에 무게감을 더합니다.',
        avatar: avatar('사다', 'd946ef'),
        tags: ['진중한', '오디오북', '역사'],
        gender: 'Male',
        language: '한국어',
        accent: '표준어',
        age: 'middle_aged',
        useCase: 'audiobook',
        previewUrl: '',
        sampleText: '1950년, 한반도에는 전쟁의 먹구름이 드리워지고 있었다.',
    },
    {
        id: 'schedar',
        googleVoiceId: 'ko-KR-Chirp3-HD-Schedar',
        name: '셰다르',
        nameEn: 'Schedar',
        description: '안정적이고 단단한 HD 남성 보이스. 교육과 강의에서 명확한 전달력을 발휘합니다.',
        avatar: avatar('셰다', 'fb923c'),
        tags: ['안정적', '교육', '강의'],
        gender: 'Male',
        language: '한국어',
        accent: '표준어',
        age: 'middle_aged',
        useCase: 'educational',
        previewUrl: '',
        sampleText: '자, 그러면 이 개념을 좀 더 자세히 살펴보겠습니다.',
    },
    {
        id: 'umbriel',
        googleVoiceId: 'ko-KR-Chirp3-HD-Umbriel',
        name: '움브리엘',
        nameEn: 'Umbriel',
        description: '부드럽고 포근한 HD 남성 보이스. 명상과 수면 이야기에 평화로운 분위기를 만듭니다.',
        avatar: avatar('움브', '14b8a6'),
        tags: ['포근한', '명상', '수면'],
        gender: 'Male',
        language: '한국어',
        accent: '표준어',
        age: 'middle_aged',
        useCase: 'meditation',
        previewUrl: '',
        sampleText: '편안하게 누워서, 천천히 호흡을 가다듬어 보세요.',
    },

    // ===================================================================
    // 🇰🇷 KOREAN CLASSIC VOICES — Neural2 / Wavenet (추가 보이스)
    // ===================================================================
    {
        id: 'neural2-a',
        googleVoiceId: 'ko-KR-Neural2-A',
        name: '하늘 (Neural)',
        nameEn: 'Neural2-A',
        description: 'Google Neural2 여성 보이스. 깔끔하고 정확한 발음으로 범용적으로 사용 가능합니다.',
        avatar: avatar('하늘', '6366f1'),
        tags: ['깔끔한', '범용', 'Neural'],
        gender: 'Female',
        language: '한국어',
        accent: '표준어',
        age: 'young',
        useCase: 'general',
        previewUrl: '',
        sampleText: '안녕하세요, 반갑습니다. 무엇을 도와드릴까요?',
    },
    {
        id: 'neural2-b',
        googleVoiceId: 'ko-KR-Neural2-B',
        name: '소리 (Neural)',
        nameEn: 'Neural2-B',
        description: 'Google Neural2 여성 보이스. 하늘보다 약간 낮은 톤으로 안정적인 느낌을 줍니다.',
        avatar: avatar('소리', 'ec4899'),
        tags: ['안정적', '낮은톤', 'Neural'],
        gender: 'Female',
        language: '한국어',
        accent: '표준어',
        age: 'middle_aged',
        useCase: 'informative',
        previewUrl: '',
        sampleText: '이번 주말 날씨는 전국적으로 맑겠습니다.',
    },
    {
        id: 'neural2-c',
        googleVoiceId: 'ko-KR-Neural2-C',
        name: '민수 (Neural)',
        nameEn: 'Neural2-C',
        description: 'Google Neural2 남성 보이스. 명확하고 깔끔한 톤으로 안내와 공지에 적합합니다.',
        avatar: avatar('민수', '1e293b'),
        tags: ['명확한', '안내', 'Neural'],
        gender: 'Male',
        language: '한국어',
        accent: '표준어',
        age: 'middle_aged',
        useCase: 'announcement',
        previewUrl: '',
        sampleText: '고객님, 주문하신 상품이 배송 준비 중입니다.',
    },

    // ===================================================================
    // 🇺🇸 ENGLISH VOICES — Google Cloud TTS Chirp3-HD (여성 5 + 남성 5)
    // ===================================================================

    // --- English Female ---
    {
        id: 'en-achernar',
        googleVoiceId: 'en-US-Chirp3-HD-Achernar',
        name: '에이커나',
        nameEn: 'Achernar',
        description: '따뜻하고 자연스러운 영어 여성 보이스. 팟캐스트와 내레이션에 편안한 분위기를 만듭니다.',
        avatar: avatar('Ach', '3b82f6'),
        tags: ['Warm', 'Narration', 'Natural'],
        gender: 'Female',
        language: 'English',
        accent: 'American',
        age: 'young',
        useCase: 'narration',
        previewUrl: '',
        sampleText: 'Hello everyone, welcome to today\'s episode. I have something truly special to share with you.',
    },
    {
        id: 'en-aoede',
        googleVoiceId: 'en-US-Chirp3-HD-Aoede',
        name: '아오에데',
        nameEn: 'Aoede',
        description: '감성적이고 부드러운 영어 여성 보이스. 오디오북과 드라마에서 깊은 몰입감을 선사합니다.',
        avatar: avatar('Aoe', 'ec4899'),
        tags: ['Emotional', 'Audiobook', 'Drama'],
        gender: 'Female',
        language: 'English',
        accent: 'American',
        age: 'young',
        useCase: 'audiobook',
        previewUrl: '',
        sampleText: 'The rain fell softly against the window, and she knew in her heart that everything was about to change.',
    },
    {
        id: 'en-kore',
        googleVoiceId: 'en-US-Chirp3-HD-Kore',
        name: '코레',
        nameEn: 'Kore',
        description: '밝고 친근한 영어 여성 보이스. 튜토리얼과 교육 콘텐츠에서 이해하기 쉬운 설명을 합니다.',
        avatar: avatar('Kore', 'f59e0b'),
        tags: ['Friendly', 'Tutorial', 'Education'],
        gender: 'Female',
        language: 'English',
        accent: 'American',
        age: 'young',
        useCase: 'educational',
        previewUrl: '',
        sampleText: 'Alright, let me walk you through this step by step. It\'s easier than you think!',
    },
    {
        id: 'en-leda',
        googleVoiceId: 'en-US-Chirp3-HD-Leda',
        name: '레다',
        nameEn: 'Leda',
        description: '세련되고 전문적인 영어 여성 보이스. 비즈니스와 기업 프레젠테이션에 품격을 더합니다.',
        avatar: avatar('Leda', '8b5cf6'),
        tags: ['Professional', 'Business', 'Elegant'],
        gender: 'Female',
        language: 'English',
        accent: 'American',
        age: 'middle_aged',
        useCase: 'corporate',
        previewUrl: '',
        sampleText: 'Our strategic vision for this quarter focuses on innovation, growth, and sustainable impact.',
    },
    {
        id: 'en-zephyr',
        googleVoiceId: 'en-US-Chirp3-HD-Zephyr',
        name: '제퍼',
        nameEn: 'Zephyr',
        description: '경쾌하고 에너지 넘치는 영어 여성 보이스. 소셜 미디어와 라이프스타일 콘텐츠에 활기를 줍니다.',
        avatar: avatar('Zeph', 'f43f5e'),
        tags: ['Energetic', 'Social Media', 'Fun'],
        gender: 'Female',
        language: 'English',
        accent: 'American',
        age: 'young',
        useCase: 'social_media',
        previewUrl: '',
        sampleText: 'Oh my gosh, you guys, this is literally the best thing I have ever tried!',
    },

    // --- English Male ---
    {
        id: 'en-achird',
        googleVoiceId: 'en-US-Chirp3-HD-Achird',
        name: '아키르드',
        nameEn: 'Achird',
        description: '깊고 신뢰감 있는 영어 남성 보이스. 다큐멘터리와 역사 내레이션에 무게감을 더합니다.',
        avatar: avatar('Ach', '1e293b'),
        tags: ['Deep', 'Documentary', 'Trustworthy'],
        gender: 'Male',
        language: 'English',
        accent: 'American',
        age: 'middle_aged',
        useCase: 'narration',
        previewUrl: '',
        sampleText: 'In the vast expanse of the universe, there are stories waiting to be told.',
    },
    {
        id: 'en-charon',
        googleVoiceId: 'en-US-Chirp3-HD-Charon',
        name: '카론',
        nameEn: 'Charon',
        description: '낮고 묵직한 영어 남성 보이스. 미스터리와 스릴러에서 긴장감을 극대화합니다.',
        avatar: avatar('Char', '475569'),
        tags: ['Dark', 'Mystery', 'Thriller'],
        gender: 'Male',
        language: 'English',
        accent: 'American',
        age: 'middle_aged',
        useCase: 'mystery',
        previewUrl: '',
        sampleText: 'The door creaked open slowly, revealing nothing but darkness and silence within.',
    },
    {
        id: 'en-fenrir',
        googleVoiceId: 'en-US-Chirp3-HD-Fenrir',
        name: '펜리르',
        nameEn: 'Fenrir',
        description: '강렬하고 파워풀한 영어 남성 보이스. 게이밍과 액션 콘텐츠에 드라마틱한 임팩트를 줍니다.',
        avatar: avatar('Fen', '7c3aed'),
        tags: ['Powerful', 'Gaming', 'Action'],
        gender: 'Male',
        language: 'English',
        accent: 'American',
        age: 'young',
        useCase: 'gaming',
        previewUrl: '',
        sampleText: 'Warriors, stand your ground! The final battle begins now!',
    },
    {
        id: 'en-puck',
        googleVoiceId: 'en-US-Chirp3-HD-Puck',
        name: '퍽',
        nameEn: 'Puck',
        description: '유쾌하고 친근한 영어 남성 보이스. 코미디와 캐주얼 콘텐츠에서 재미를 더합니다.',
        avatar: avatar('Puck', '059669'),
        tags: ['Playful', 'Comedy', 'Casual'],
        gender: 'Male',
        language: 'English',
        accent: 'American',
        age: 'young',
        useCase: 'entertainment',
        previewUrl: '',
        sampleText: 'So there I was, standing in line, and you will never guess what happened next!',
    },
    {
        id: 'en-enceladus',
        googleVoiceId: 'en-US-Chirp3-HD-Enceladus',
        name: '엔셀라두스',
        nameEn: 'Enceladus',
        description: '안정적이고 명확한 영어 남성 보이스. 뉴스와 정보 전달에 전문적인 톤을 제공합니다.',
        avatar: avatar('Enc', '0891b2'),
        tags: ['Steady', 'News', 'Professional'],
        gender: 'Male',
        language: 'English',
        accent: 'American',
        age: 'middle_aged',
        useCase: 'news',
        previewUrl: '',
        sampleText: 'Good evening. Here is your update on the latest developments around the world.',
    },
];
